<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <SharpProsperoRoot Condition="'$(SharpProsperoRoot)' == '' And Exists('$(MSBuildThisFileDirectory)..\SharpProspero\build\Prospero.App.props')">$(MSBuildThisFileDirectory)..\SharpProspero</SharpProsperoRoot>
    <SharpProsperoRoot Condition="'$(SharpProsperoRoot)' == ''">$(SHARPPROSPERO_ROOT)</SharpProsperoRoot>
  </PropertyGroup>

  <Import Project="$(SharpProsperoRoot)\build\Prospero.App.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ProsperoMultiTools</RootNamespace>
    <AssemblyName>ProsperoMultiTools</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <ProsperoModuleName>eboot.bin</ProsperoModuleName>
    <ProsperoHeapHardLimitBytes>402653184</ProsperoHeapHardLimitBytes>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SharpProsperoRoot)\src\SharpProspero\SharpProspero.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="sce_sys\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="src\Data\emulator-manifest.json" LogicalName="emulator-manifest.json" />
  </ItemGroup>

  <Import Project="$(SharpProsperoRoot)\build\Prospero.App.targets" />

</Project>
